name: RegrowthWorldBorderExpander
version: ${project.version}
main: org.lushplugins.regrowthworldborderexpander.RegrowthWorldBorderExpander
api-version: '1.21'
github-repo: ProjectOwner/RegrowthWorldBorderExpander
